// <auto-generated />
using System;
using Flowqueue_Backend.shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flowqueue_Backend.shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Flowqueue_Backend.Institutions.Domain.Model.Aggregates.BranchOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("district");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int")
                        .HasColumnName("institution_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("schedule");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_branch_offices");

                    b.HasIndex("InstitutionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_branch_offices_institution_id_name");

                    b.ToTable("branch_offices");
                });

            modelBuilder.Entity("Flowqueue_Backend.Institutions.Domain.Model.Aggregates.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_institutions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_institutions_name");

                    b.ToTable("institutions");
                });

            modelBuilder.Entity("Flowqueue_Backend.Institutions.Domain.Model.Aggregates.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AverageDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("average_duration_minutes");

                    b.Property<int>("BranchOfficeId")
                        .HasColumnType("int")
                        .HasColumnName("branch_office_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("prefix");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_services");

                    b.HasIndex("BranchOfficeId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_services_branch_office_id_name");

                    b.ToTable("services");
                });

            modelBuilder.Entity("Flowqueue_Backend.Queueing.Domain.Model.Aggregates.Turn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BranchOfficeId")
                        .HasColumnType("int")
                        .HasColumnName("branch_office_id");

                    b.Property<DateTimeOffset?>("CalledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("called_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CitizenDocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("citizen_document_number");

                    b.Property<string>("CitizenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("citizen_name");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("MarkedAbsentAt")
                        .HasColumnType("datetime")
                        .HasColumnName("marked_absent_at");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("registered_at");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ticket_code");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("int")
                        .HasColumnName("turn_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_turns");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("i_x_turns_service_id");

                    b.HasIndex("TicketCode")
                        .IsUnique()
                        .HasDatabaseName("i_x_turns_ticket_code");

                    b.HasIndex("BranchOfficeId", "ServiceId", "TurnNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_turns_branch_office_id_service_id_turn_number");

                    b.ToTable("turns");
                });

            modelBuilder.Entity("Flowqueue_Backend.Institutions.Domain.Model.Aggregates.BranchOffice", b =>
                {
                    b.HasOne("Flowqueue_Backend.Institutions.Domain.Model.Aggregates.Institution", null)
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_branch_offices__institutions_institution_id");
                });

            modelBuilder.Entity("Flowqueue_Backend.Institutions.Domain.Model.Aggregates.Service", b =>
                {
                    b.HasOne("Flowqueue_Backend.Institutions.Domain.Model.Aggregates.BranchOffice", null)
                        .WithMany()
                        .HasForeignKey("BranchOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_services_branch_offices_branch_office_id");
                });

            modelBuilder.Entity("Flowqueue_Backend.Queueing.Domain.Model.Aggregates.Turn", b =>
                {
                    b.HasOne("Flowqueue_Backend.Institutions.Domain.Model.Aggregates.BranchOffice", null)
                        .WithMany()
                        .HasForeignKey("BranchOfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_turns_branch_offices_branch_office_id");

                    b.HasOne("Flowqueue_Backend.Institutions.Domain.Model.Aggregates.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_turns_services_service_id");
                });
#pragma warning restore 612, 618
        }
    }
}
